---
# IP address and port of the robot
ip: "128.32.175.186"
port: 5556

# IP address of web viewer
web_viewer_ip: "128.32.175.81"
web_viewer_port: 5000

# Robot ID
robot_id: 3

# General config parameters
sticky_gripper_num_steps: 1 # I'm thinking that for online improvement, we should turn off sticky gripper
env_params:
  camera_topics:
    - name: "/blue/image_raw"
      flip: false
  override_workspace_boundaries:
    - - -20.0
      - -20.0
      - -20.0
      - -1.57
      - 0
    - - 20.0
      - 20.0
      - 20.0
      - 1.57
      - 0
  move_duration: 0.3
video_save_path: ""
shoulder_camera_image_size: 256 # size of image returned by shoulder cam
initial_eep:
  - 0.3
  - 0.0
  - 0.15
  - 0
  - 0
  - 0
  - 1
manual_workspace_bounds:
  x:
    - 0.25376111
    - 0.44158756
  y:
    - -0.17615086
    - 0.18689521
  z:
    - 0.0187575
    - 0.13504307
